### ISSUE TITLE
访问找不到这个templates/index.html，想问一下怎么解决？

### ISSUE THREAD

**Issue by lilixin666** [xuanbo/kettle-web#20]
[dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is jetbrick.io.resource.ResourceNotFoundException: templates/index.html] with root cause
jetbrick.io.resource.ResourceNotFoundException: templates/index.html

**Comment by xuanbo** [comment]
@lilixin666 是存在额外的改动吗，我这边是正常的

**Comment by lilixin666** [comment]
> @lilixin666是存在的额外的切换吗，我现在是正常的

我没有改动，就是拉下来直接使用，执行就报这个错？

**Comment by lilixin666** [comment]
现在又换问题了？
org.pentaho.di.core.exception.KettleXMLException: 
Unable to load the job from XML file [demo.kjb]

Unable to read file [file:///E:/Apache Camel/kettle/kettle-web-master/demo.kjb]
Could not read from "file:///E:/Apache Camel/kettle/kettle-web-master/demo.kjb" because it is not a file.


	at org.pentaho.di.job.JobMeta.<init>(JobMeta.java:786) ~[kettle-engine-7.1.0.0-12.jar:7.1.0.0-12]
	at org.pentaho.di.job.JobMeta.<init>(JobMeta.java:758) ~[kettle-engine-7.1.0.0-12.jar:7.1.0.0-12]
	at org.pentaho.di.job.JobMeta.<init>(JobMeta.java:733) ~[kettle-engine-7.1.0.0-12.jar:7.1.0.0-12]
	at com.xinqing.etl.kettleweb.job.JobSubmitter.lambda$submit$0(JobSubmitter.java:56) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111]
这个问题你有遇到吗？

**Comment by xuanbo** [comment]
@lilixin666 没有遇到这个问题，你可以写写单元测试，看看是不是文件路径问题

**Comment by lilixin666** [comment]
没有问题，测试了。
